spring.application.name=icpus
spring.datasource.url=jdbc:postgresql://localhost:5432/icpusdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true